//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Aoc2021 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Aoc2021Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Aoc2021Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Aoc2021.Aoc2021Data", typeof(Aoc2021Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;depths&quot;:[
        ///184,
        ///205,
        ///211,
        ///213,
        ///227,
        ///225,
        ///224,
        ///228,
        ///232,
        ///231,
        ///217,
        ///230,
        ///231,
        ///237,
        ///250,
        ///257,
        ///256,
        ///255,
        ///260,
        ///261,
        ///250,
        ///252,
        ///243,
        ///242,
        ///240,
        ///248,
        ///253,
        ///261,
        ///262,
        ///241,
        ///227,
        ///234,
        ///235,
        ///236,
        ///237,
        ///264,
        ///267,
        ///246,
        ///249,
        ///237,
        ///258,
        ///255,
        ///257,
        ///259,
        ///253,
        ///262,
        ///263,
        ///271,
        ///252,
        ///254,
        ///249,
        ///255,
        ///258,
        ///267,
        ///278,
        ///281,
        ///282,
        ///287,
        ///298,
        ///292,
        ///282,
        ///283,
        ///286,
        ///281,
        ///274,
        ///272,
        ///268,
        ///267,
        ///272,
        ///288,
        ///293,
        ///316,
        ///348,
        ///340,
        ///337,
        ///341,
        ///344,
        ///343,
        ///358,
        ///356,
        ///358,
        ///359,
        ///364,
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;depths&quot;:[199,
        ///200,
        ///208,
        ///210,
        ///200,
        ///207,
        ///240,
        ///269,
        ///260,
        ///263]}.
        /// </summary>
        internal static string Day1Sample {
            get {
                return ResourceManager.GetString("Day1Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;moves&quot;:[
        ///&quot;forward 3&quot;,
        ///&quot;down 9&quot;,
        ///&quot;forward 6&quot;,
        ///&quot;down 3&quot;,
        ///&quot;forward 8&quot;,
        ///&quot;down 3&quot;,
        ///&quot;down 4&quot;,
        ///&quot;forward 3&quot;,
        ///&quot;forward 5&quot;,
        ///&quot;up 7&quot;,
        ///&quot;forward 1&quot;,
        ///&quot;forward 1&quot;,
        ///&quot;forward 5&quot;,
        ///&quot;down 8&quot;,
        ///&quot;down 5&quot;,
        ///&quot;forward 3&quot;,
        ///&quot;forward 2&quot;,
        ///&quot;forward 4&quot;,
        ///&quot;down 7&quot;,
        ///&quot;up 2&quot;,
        ///&quot;up 2&quot;,
        ///&quot;down 5&quot;,
        ///&quot;down 5&quot;,
        ///&quot;down 8&quot;,
        ///&quot;down 2&quot;,
        ///&quot;down 4&quot;,
        ///&quot;forward 8&quot;,
        ///&quot;forward 8&quot;,
        ///&quot;up 2&quot;,
        ///&quot;down 2&quot;,
        ///&quot;up 8&quot;,
        ///&quot;up 4&quot;,
        ///&quot;forward 7&quot;,
        ///&quot;up 8&quot;,
        ///&quot;down 6&quot;,
        ///&quot;forward 9&quot;,
        ///&quot;forward 6&quot;,
        ///&quot;forward 5&quot;,
        ///&quot;up 1&quot;,
        ///&quot;forward 6&quot;,
        ///&quot;forward 8&quot;,
        ///&quot;down  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;moves&quot;:[
        ///      &quot;forward 5&quot;,
        ///      &quot;down 5&quot;,
        ///      &quot;forward 8&quot;,
        ///      &quot;up 3&quot;,
        ///      &quot;down 8&quot;,
        ///      &quot;forward 2&quot;
        ///   ]
        ///}.
        /// </summary>
        internal static string Day2Sample {
            get {
                return ResourceManager.GetString("Day2Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;data&quot;:[
        ///&quot;010100010111&quot;,
        ///&quot;100100100110&quot;,
        ///&quot;100110111001&quot;,
        ///&quot;011001011011&quot;,
        ///&quot;010000110111&quot;,
        ///&quot;000011101001&quot;,
        ///&quot;011000011101&quot;,
        ///&quot;101111011111&quot;,
        ///&quot;011001011010&quot;,
        ///&quot;111100001001&quot;,
        ///&quot;111111000110&quot;,
        ///&quot;100010100110&quot;,
        ///&quot;011100100100&quot;,
        ///&quot;011111010000&quot;,
        ///&quot;111010001100&quot;,
        ///&quot;010111001110&quot;,
        ///&quot;100010100100&quot;,
        ///&quot;101000010000&quot;,
        ///&quot;011101110100&quot;,
        ///&quot;100010011000&quot;,
        ///&quot;001111110011&quot;,
        ///&quot;111001100001&quot;,
        ///&quot;010000011001&quot;,
        ///&quot;000011101010&quot;,
        ///&quot;100010101100&quot;,
        ///&quot;111011100010&quot;,
        ///&quot;110000100001&quot;,
        ///&quot;101010110001&quot;,
        ///&quot;111101110101&quot;,
        ///&quot;0010100 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;data&quot;:[&quot;00100&quot;,
        ///&quot;11110&quot;,
        ///&quot;10110&quot;,
        ///&quot;10111&quot;,
        ///&quot;10101&quot;,
        ///&quot;01111&quot;,
        ///&quot;00111&quot;,
        ///&quot;11100&quot;,
        ///&quot;10000&quot;,
        ///&quot;11001&quot;,
        ///&quot;00010&quot;,
        ///&quot;01010&quot;]}.
        /// </summary>
        internal static string Day3Sample {
            get {
                return ResourceManager.GetString("Day3Sample", resourceCulture);
            }
        }
    }
}
