//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Aoc2021 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Aoc2021Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Aoc2021Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Aoc2021.Aoc2021Data", typeof(Aoc2021Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;depths&quot;:[
        ///184,
        ///205,
        ///211,
        ///213,
        ///227,
        ///225,
        ///224,
        ///228,
        ///232,
        ///231,
        ///217,
        ///230,
        ///231,
        ///237,
        ///250,
        ///257,
        ///256,
        ///255,
        ///260,
        ///261,
        ///250,
        ///252,
        ///243,
        ///242,
        ///240,
        ///248,
        ///253,
        ///261,
        ///262,
        ///241,
        ///227,
        ///234,
        ///235,
        ///236,
        ///237,
        ///264,
        ///267,
        ///246,
        ///249,
        ///237,
        ///258,
        ///255,
        ///257,
        ///259,
        ///253,
        ///262,
        ///263,
        ///271,
        ///252,
        ///254,
        ///249,
        ///255,
        ///258,
        ///267,
        ///278,
        ///281,
        ///282,
        ///287,
        ///298,
        ///292,
        ///282,
        ///283,
        ///286,
        ///281,
        ///274,
        ///272,
        ///268,
        ///267,
        ///272,
        ///288,
        ///293,
        ///316,
        ///348,
        ///340,
        ///337,
        ///341,
        ///344,
        ///343,
        ///358,
        ///356,
        ///358,
        ///359,
        ///364,
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01 {
            get {
                return ResourceManager.GetString("Day01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 184
        ///205
        ///211
        ///213
        ///227
        ///225
        ///224
        ///228
        ///232
        ///231
        ///217
        ///230
        ///231
        ///237
        ///250
        ///257
        ///256
        ///255
        ///260
        ///261
        ///250
        ///252
        ///243
        ///242
        ///240
        ///248
        ///253
        ///261
        ///262
        ///241
        ///227
        ///234
        ///235
        ///236
        ///237
        ///264
        ///267
        ///246
        ///249
        ///237
        ///258
        ///255
        ///257
        ///259
        ///253
        ///262
        ///263
        ///271
        ///252
        ///254
        ///249
        ///255
        ///258
        ///267
        ///278
        ///281
        ///282
        ///287
        ///298
        ///292
        ///282
        ///283
        ///286
        ///281
        ///274
        ///272
        ///268
        ///267
        ///272
        ///288
        ///293
        ///316
        ///348
        ///340
        ///337
        ///341
        ///344
        ///343
        ///358
        ///356
        ///358
        ///359
        ///364
        ///366
        ///365
        ///368
        ///384
        ///385
        ///393
        ///387
        ///388
        ///369
        ///376
        ///393
        ///395
        ///400
        ///401
        ///402
        ///401
        ///404
        ///382
        ///381
        ///38 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01A {
            get {
                return ResourceManager.GetString("Day01A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;depths&quot;:[199,
        ///200,
        ///208,
        ///210,
        ///200,
        ///207,
        ///240,
        ///269,
        ///260,
        ///263]}.
        /// </summary>
        internal static string Day01Sample {
            get {
                return ResourceManager.GetString("Day01Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 199
        ///200
        ///208
        ///210
        ///200
        ///207
        ///240
        ///269
        ///260
        ///263.
        /// </summary>
        internal static string Day01SampleA {
            get {
                return ResourceManager.GetString("Day01SampleA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;moves&quot;:[
        ///&quot;forward 3&quot;,
        ///&quot;down 9&quot;,
        ///&quot;forward 6&quot;,
        ///&quot;down 3&quot;,
        ///&quot;forward 8&quot;,
        ///&quot;down 3&quot;,
        ///&quot;down 4&quot;,
        ///&quot;forward 3&quot;,
        ///&quot;forward 5&quot;,
        ///&quot;up 7&quot;,
        ///&quot;forward 1&quot;,
        ///&quot;forward 1&quot;,
        ///&quot;forward 5&quot;,
        ///&quot;down 8&quot;,
        ///&quot;down 5&quot;,
        ///&quot;forward 3&quot;,
        ///&quot;forward 2&quot;,
        ///&quot;forward 4&quot;,
        ///&quot;down 7&quot;,
        ///&quot;up 2&quot;,
        ///&quot;up 2&quot;,
        ///&quot;down 5&quot;,
        ///&quot;down 5&quot;,
        ///&quot;down 8&quot;,
        ///&quot;down 2&quot;,
        ///&quot;down 4&quot;,
        ///&quot;forward 8&quot;,
        ///&quot;forward 8&quot;,
        ///&quot;up 2&quot;,
        ///&quot;down 2&quot;,
        ///&quot;up 8&quot;,
        ///&quot;up 4&quot;,
        ///&quot;forward 7&quot;,
        ///&quot;up 8&quot;,
        ///&quot;down 6&quot;,
        ///&quot;forward 9&quot;,
        ///&quot;forward 6&quot;,
        ///&quot;forward 5&quot;,
        ///&quot;up 1&quot;,
        ///&quot;forward 6&quot;,
        ///&quot;forward 8&quot;,
        ///&quot;down  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02 {
            get {
                return ResourceManager.GetString("Day02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;moves&quot;:[
        ///      &quot;forward 5&quot;,
        ///      &quot;down 5&quot;,
        ///      &quot;forward 8&quot;,
        ///      &quot;up 3&quot;,
        ///      &quot;down 8&quot;,
        ///      &quot;forward 2&quot;
        ///   ]
        ///}.
        /// </summary>
        internal static string Day02Sample {
            get {
                return ResourceManager.GetString("Day02Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;data&quot;:[
        ///&quot;010100010111&quot;,
        ///&quot;100100100110&quot;,
        ///&quot;100110111001&quot;,
        ///&quot;011001011011&quot;,
        ///&quot;010000110111&quot;,
        ///&quot;000011101001&quot;,
        ///&quot;011000011101&quot;,
        ///&quot;101111011111&quot;,
        ///&quot;011001011010&quot;,
        ///&quot;111100001001&quot;,
        ///&quot;111111000110&quot;,
        ///&quot;100010100110&quot;,
        ///&quot;011100100100&quot;,
        ///&quot;011111010000&quot;,
        ///&quot;111010001100&quot;,
        ///&quot;010111001110&quot;,
        ///&quot;100010100100&quot;,
        ///&quot;101000010000&quot;,
        ///&quot;011101110100&quot;,
        ///&quot;100010011000&quot;,
        ///&quot;001111110011&quot;,
        ///&quot;111001100001&quot;,
        ///&quot;010000011001&quot;,
        ///&quot;000011101010&quot;,
        ///&quot;100010101100&quot;,
        ///&quot;111011100010&quot;,
        ///&quot;110000100001&quot;,
        ///&quot;101010110001&quot;,
        ///&quot;111101110101&quot;,
        ///&quot;0010100 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03 {
            get {
                return ResourceManager.GetString("Day03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;data&quot;:[&quot;00100&quot;,
        ///&quot;11110&quot;,
        ///&quot;10110&quot;,
        ///&quot;10111&quot;,
        ///&quot;10101&quot;,
        ///&quot;01111&quot;,
        ///&quot;00111&quot;,
        ///&quot;11100&quot;,
        ///&quot;10000&quot;,
        ///&quot;11001&quot;,
        ///&quot;00010&quot;,
        ///&quot;01010&quot;]}.
        /// </summary>
        internal static string Day03Sample {
            get {
                return ResourceManager.GetString("Day03Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31,50,68,16,25,15,28,80,41,8,75,45,96,9,3,98,83,27,62,42,59,99,95,13,55,10,23,84,18,76,87,56,88,66,1,58,92,89,19,54,85,74,39,93,77,26,30,52,69,48,91,73,72,38,64,53,32,51,6,29,17,90,34,61,70,4,7,57,44,97,82,37,43,14,81,65,11,22,5,36,71,35,78,12,0,94,47,49,33,79,63,86,40,21,24,46,20,2,67,60
        ///
        ///95 91 54 75 45
        ///46 94 39 44 85
        ///31 43 24  2 70
        ///90 58  4 30 77
        ///13 26 38 52 34
        ///
        ///68 14 99 63 46
        ///67 16 82 10  8
        ///55 52 41 51  4
        ///90 17 32 44 74
        ///89 94 73 56 36
        ///
        /// 6 91  2 28 71
        /// 7 88 37 21 36
        ///95 32 84 57  8
        ///13 79 8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04 {
            get {
                return ResourceManager.GetString("Day04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1
        ///
        ///22 13 17 11  0
        /// 8  2 23  4 24
        ///21  9 14 16  7
        /// 6 10  3 18  5
        /// 1 12 20 15 19
        ///
        /// 3 15  0  2 22
        /// 9 18 13 17  5
        ///19  8  7 25 23
        ///20 11 10 24  4
        ///14 21 16 12  6
        ///
        ///14 21 17 24  4
        ///10 16 15  9 19
        ///18  8 23 26 20
        ///22 11 13  6  5
        /// 2  0 12  3  7.
        /// </summary>
        internal static string Day04Sample {
            get {
                return ResourceManager.GetString("Day04Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 959,103 -&gt; 139,923
        ///899,63 -&gt; 899,53
        ///591,871 -&gt; 364,644
        ///739,913 -&gt; 310,484
        ///460,309 -&gt; 460,705
        ///351,389 -&gt; 351,837
        ///420,55 -&gt; 420,541
        ///916,520 -&gt; 382,520
        ///136,604 -&gt; 295,604
        ///343,59 -&gt; 142,59
        ///951,206 -&gt; 806,206
        ///984,950 -&gt; 61,27
        ///739,388 -&gt; 988,388
        ///374,370 -&gt; 644,370
        ///403,504 -&gt; 798,899
        ///943,535 -&gt; 229,535
        ///149,227 -&gt; 583,661
        ///62,126 -&gt; 62,352
        ///131,391 -&gt; 131,717
        ///254,944 -&gt; 254,220
        ///572,111 -&gt; 572,47
        ///336,249 -&gt; 830,743
        ///898,858 -&gt; 203,163
        ///203,320 -&gt; 825,942
        ///19,318 -&gt; 19,120
        ///740,432 -&gt; 740,39
        ///591,3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day05 {
            get {
                return ResourceManager.GetString("Day05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,9 -&gt; 5,9
        ///8,0 -&gt; 0,8
        ///9,4 -&gt; 3,4
        ///2,2 -&gt; 2,1
        ///7,0 -&gt; 7,4
        ///6,4 -&gt; 2,0
        ///0,9 -&gt; 2,9
        ///3,4 -&gt; 1,4
        ///0,0 -&gt; 8,8
        ///5,5 -&gt; 8,2.
        /// </summary>
        internal static string Day05Sample {
            get {
                return ResourceManager.GetString("Day05Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5,4,3,5,1,1,2,1,2,1,3,2,3,4,5,1,2,4,3,2,5,1,4,2,1,1,2,5,4,4,4,1,5,4,5,2,1,2,5,5,4,1,3,1,4,2,4,2,5,1,3,5,3,2,3,1,1,4,5,2,4,3,1,5,5,1,3,1,3,2,2,4,1,3,4,3,3,4,1,3,4,3,4,5,2,1,1,1,4,5,5,1,1,3,2,4,1,2,2,2,4,1,2,5,5,1,4,5,2,4,2,1,5,4,1,3,4,1,2,3,1,5,1,3,4,5,4,1,4,3,3,3,5,5,1,1,5,1,5,5,1,5,2,1,5,1,2,3,5,5,1,3,3,1,5,3,4,3,4,3,2,5,2,1,2,5,1,1,1,1,5,1,1,4,3,3,5,1,1,1,4,4,1,3,3,5,5,4,3,2,1,2,2,3,4,1,5,4,3,1,1,5,1,4,2,3,2,2,3,4,1,3,4,1,4,3,4,3,1,3,3,1,1,4,1,1,1,4,5,3,1,1,2,5,2,5,1,5,3,3,1,3,5,5,1,5,4,3,1,5,1,1,5,5,1,1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day06 {
            get {
                return ResourceManager.GetString("Day06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3,4,3,1,2.
        /// </summary>
        internal static string Day06Sample {
            get {
                return ResourceManager.GetString("Day06Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1101,1,29,67,1102,0,1,65,1008,65,35,66,1005,66,28,1,67,65,20,4,0,1001,65,1,65,1106,0,8,99,35,67,101,99,105,32,110,39,101,115,116,32,112,97,115,32,117,110,101,32,105,110,116,99,111,100,101,32,112,114,111,103,114,97,109,10,20,1091,861,228,628,186,980,996,710,541,354,1611,69,1331,91,1220,447,523,38,1286,244,643,1069,566,70,155,1710,1266,120,302,72,232,387,1086,278,1122,605,1559,98,111,1816,795,543,1217,304,356,129,839,704,49,523,370,74,13,232,179,101,664,892,266,622,197,404,147,882,435,504,48,766,684,1362,136, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day07 {
            get {
                return ResourceManager.GetString("Day07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16,1,2,0,4,2,7,1,2,14.
        /// </summary>
        internal static string Day07Sample {
            get {
                return ResourceManager.GetString("Day07Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fdeba beagfd gbafe dagb dbf ecfad bd dgcaefb fbecgd abfecg | dgba dfb ecadf bdf
        ///dgfc egdbaf afgcbe eafdbcg bcgad bdg fdbacg gd ecabd bafgc | gd gbd dg febgac
        ///dfebc bceadf ebacf gdceb fd dfea cdgfba afbgec dfb fdaecbg | cgafbde efbagc faed gecdb
        ///dbaef fabgd fcaedb cgadf aefbgd cabefg gfb bceagdf bg ebdg | gdbfae geafdbc bafgdce dbgfa
        ///aebgd adg dg dgcabef facedg cfaebd dfbega begca bfgd dbafe | abdecf eafbd fdgb ebdfgca
        ///bae febac abcgf eabfgd cbagfd gefcba abedfcg efcda eb becg | fcgab gafbed aedcfbg eb        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day08 {
            get {
                return ResourceManager.GetString("Day08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be cfbegad cbdgef fgaecd cgeb fdcge agebfd fecdb fabcd edb | fdgacbe cefdb cefbgd gcbe
        ///edbfga begcd cbg gc gcadebf fbgde acbgfd abcde gfcbed gfec | fcgedb cgb dgebacf gc
        ///fgaebd cg bdaec gdafb agbcfd gdcbef bgcad gfac gcb cdgabef | cg cg fdcagb cbg
        ///fbegcd cbd adcefb dageb afcb bc aefdc ecdab fgdeca fcdbega | efabcd cedba gadfec cb
        ///aecbfdg fbg gf bafeg dbefa fcge gcbea fcaegb dgceab fcbdga | gecf egdcabf bgf bfgea
        ///fgeab ca afcebg bdacfeg cfaedg gcfdb baec bfadeg bafgc acf | gebdcfa ecba ca fadegcb
        ///dbcfg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day08Sample {
            get {
                return ResourceManager.GetString("Day08Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0197653456789987679545987978921245689901497654212455689767899878999979653246892123569876467899212346
        ///9989542349899986578959976557890134599892398943201234678956789467989867932135789012398764345678923456
        ///8679931298999765459898765445921247987689459865432345889345892399876546899013894123459976569799634577
        ///6567895497998764345789543239895456797535967976545467891234989989865434598954993248969987678999545798
        ///8456897986539975234568955398789967998212899597676578910395678979996423987895789356798698799997656789
        ///73 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day09 {
            get {
                return ResourceManager.GetString("Day09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2199943210
        ///3987894921
        ///9856789892
        ///8767896789
        ///9899965678.
        /// </summary>
        internal static string Day09Sample {
            get {
                return ResourceManager.GetString("Day09Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {[[&lt;{(&lt;{[{{[{[[]{}]{&lt;&gt;{}}}({&lt;&gt;()}{{}{}})]}{({[&lt;&gt;{}]({}[])})[{[{}[]](()&lt;&gt;)}&lt;[{}{}]{()&lt;&gt;}&gt;]}}]&lt;(({{{(){}}{[][]
        ///&lt;&lt;&lt;({((&lt;{&lt;([([&lt;&gt;{}]&lt;{}&lt;&gt;&gt;]{&lt;{}&lt;&gt;&gt;({}&lt;&gt;)}])&gt;}{({(([()[]]{[]()})({{}&lt;&gt;}&lt;(){}&gt;))[(&lt;&lt;&gt;&lt;&gt;&gt;[()[]]){{()[]}&lt;
        ///&lt;&lt;&lt;[(({{(([[[[&lt;&gt;&lt;&gt;][&lt;&gt;&lt;&gt;]]]([[{}{}](&lt;&gt;&lt;&gt;)][(&lt;&gt;[]){[]()}])])([[(&lt;{}&lt;&gt;&gt;(()[]))(&lt;[][]&gt;)]]{{&lt;[[]{}]{&lt;
        ///({({([{{[[[{(&lt;(){}&gt;&lt;[]{}&gt;)}]]][(&lt;&lt;([()[]](()[]))&gt;[[[{}[]]{[]&lt;&gt;}](&lt;()&gt;[()&lt;&gt;]]]&gt;(&lt;(({}&lt;&gt;){&lt;&gt;[]}){&lt;[]()&gt;}&gt;{[{(
        ///[([{(&lt;[&lt;&lt;[({&lt;[()&lt;&gt;][{}]&gt;({{}{}})}({[&lt;&gt;{}][()()]}[([][]){()[]}]))]&gt;&gt;]&gt;)&lt;&lt;[((([[{{()()}(&lt;&gt;{})} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day10 {
            get {
                return ResourceManager.GetString("Day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [({(&lt;(())[]&gt;[[{[]{&lt;()&lt;&gt;&gt;
        ///[(()[&lt;&gt;])]({[&lt;{&lt;&lt;[]&gt;&gt;(
        ///{([(&lt;{}[&lt;&gt;[]}&gt;{[]{[(&lt;()&gt;
        ///(((({&lt;&gt;}&lt;{&lt;{&lt;&gt;}{[]{[]{}
        ///[[&lt;[([]))&lt;([[{}[[()]]]
        ///[{[{({}]{}}([{[{{{}}([]
        ///{&lt;[[]]&gt;}&lt;{[{[{[]{()[[[]
        ///[&lt;(&lt;(&lt;(&lt;{}))&gt;&lt;([]([]()
        ///&lt;{([([[(&lt;&gt;()){}]&gt;(&lt;&lt;{{
        ///&lt;{([{{}}[&lt;[[[&lt;&gt;{}]]]&gt;[]].
        /// </summary>
        internal static string Day10Sample {
            get {
                return ResourceManager.GetString("Day10Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4134384626
        ///7114585257
        ///1582536488
        ///4865715538
        ///5733423513
        ///8532144181
        ///1288614583
        ///2248711141
        ///6415871681
        ///7881531438.
        /// </summary>
        internal static string Day11 {
            get {
                return ResourceManager.GetString("Day11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5483143223
        ///2745854711
        ///5264556173
        ///6141336146
        ///6357385478
        ///4167524645
        ///2176841721
        ///6882881134
        ///4846848554
        ///5283751526.
        /// </summary>
        internal static string Day11Sample {
            get {
                return ResourceManager.GetString("Day11Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nu-start
        ///rt-start
        ///db-qh
        ///PE-end
        ///sl-rt
        ///qh-end
        ///ZH-rt
        ///nu-rt
        ///PE-db
        ///db-sl
        ///nu-ZH
        ///nu-qh
        ///PE-qh
        ///ZH-db
        ///ne-end
        ///ne-ZH
        ///QG-db
        ///qh-sl
        ///ZH-qh
        ///start-ZH
        ///nu-PE
        ///uf-db
        ///ne-sl.
        /// </summary>
        internal static string Day12 {
            get {
                return ResourceManager.GetString("Day12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start-A
        ///start-b
        ///A-c
        ///A-b
        ///b-d
        ///A-end
        ///b-end.
        /// </summary>
        internal static string Day12Sample1 {
            get {
                return ResourceManager.GetString("Day12Sample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dc-end
        ///HN-start
        ///start-kj
        ///dc-start
        ///dc-HN
        ///LN-dc
        ///HN-end
        ///kj-sa
        ///kj-HN
        ///kj-dc.
        /// </summary>
        internal static string Day12Sample2 {
            get {
                return ResourceManager.GetString("Day12Sample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fs-end
        ///he-DX
        ///fs-he
        ///start-DX
        ///pj-DX
        ///end-zg
        ///zg-sl
        ///zg-pj
        ///pj-he
        ///RW-he
        ///fs-DX
        ///pj-RW
        ///zg-RW
        ///start-pj
        ///he-WI
        ///zg-he
        ///pj-fs
        ///start-RW.
        /// </summary>
        internal static string Day12Sample3 {
            get {
                return ResourceManager.GetString("Day12Sample3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 938,670
        ///246,156
        ///622,476
        ///137,296
        ///708,323
        ///1019,283
        ///415,505
        ///1043,234
        ///666,871
        ///157,893
        ///969,266
        ///1280,690
        ///987,260
        ///296,428
        ///1302,361
        ///92,168
        ///206,204
        ///937,659
        ///551,488
        ///147,456
        ///1279,42
        ///463,154
        ///407,266
        ///1153,893
        ///495,372
        ///733,459
        ///378,169
        ///48,705
        ///31,852
        ///577,571
        ///36,672
        ///1014,661
        ///441,880
        ///1305,791
        ///115,553
        ///455,267
        ///360,833
        ///915,455
        ///346,53
        ///606,367
        ///1014,513
        ///930,633
        ///190,350
        ///564,577
        ///1205,376
        ///928,462
        ///577,435
        ///825,686
        ///517,598
        ///782,119
        ///1110,539
        ///67,236
        ///77,185
        ///577,723
        ///808,855
        ///139,742
        ///865,4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day13 {
            get {
                return ResourceManager.GetString("Day13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6,10
        ///0,14
        ///9,10
        ///0,3
        ///10,4
        ///4,11
        ///6,0
        ///6,12
        ///4,1
        ///0,13
        ///10,12
        ///3,4
        ///3,0
        ///8,4
        ///1,10
        ///2,14
        ///8,10
        ///9,0
        ///
        ///fold along y=7
        ///fold along x=5.
        /// </summary>
        internal static string Day13Sample {
            get {
                return ResourceManager.GetString("Day13Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VFHKKOKKCPBONFHNPHPN
        ///
        ///VS -&gt; B
        ///HK -&gt; B
        ///FO -&gt; P
        ///NC -&gt; F
        ///VN -&gt; C
        ///BS -&gt; O
        ///HS -&gt; K
        ///NS -&gt; C
        ///CV -&gt; P
        ///NV -&gt; C
        ///PH -&gt; H
        ///PB -&gt; B
        ///PK -&gt; K
        ///HF -&gt; P
        ///FV -&gt; C
        ///NN -&gt; H
        ///VO -&gt; K
        ///VP -&gt; P
        ///BC -&gt; B
        ///KK -&gt; S
        ///OK -&gt; C
        ///PN -&gt; H
        ///SB -&gt; V
        ///KO -&gt; P
        ///KH -&gt; C
        ///KS -&gt; S
        ///FP -&gt; B
        ///PV -&gt; B
        ///BO -&gt; C
        ///OS -&gt; H
        ///NB -&gt; S
        ///SP -&gt; C
        ///HN -&gt; N
        ///FN -&gt; B
        ///PO -&gt; O
        ///FS -&gt; O
        ///NH -&gt; B
        ///SO -&gt; P
        ///OB -&gt; S
        ///KC -&gt; C
        ///OO -&gt; H
        ///BB -&gt; V
        ///SC -&gt; F
        ///NP -&gt; P
        ///SH -&gt; C
        ///BH -&gt; O
        ///BP -&gt; F
        ///CC -&gt; S
        ///BN -&gt; H
        ///SS -&gt; P
        ///BF -&gt; B
        ///VK -&gt; P
        ///OV -&gt; H
        ///FC -&gt; S
        ///VB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day14 {
            get {
                return ResourceManager.GetString("Day14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NNCB
        ///
        ///CH -&gt; B
        ///HH -&gt; N
        ///CB -&gt; H
        ///NH -&gt; C
        ///HB -&gt; C
        ///HC -&gt; B
        ///HN -&gt; C
        ///NN -&gt; C
        ///BH -&gt; H
        ///NC -&gt; B
        ///NB -&gt; B
        ///BN -&gt; B
        ///BB -&gt; N
        ///BC -&gt; B
        ///CC -&gt; N
        ///CN -&gt; C.
        /// </summary>
        internal static string Day14Sample {
            get {
                return ResourceManager.GetString("Day14Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2494188795949368426672935997553436999123973817111494977966298896479213563868828787114774871959993495
        ///7269295166912819128199218896192745233371189151296812199288995976199874739992471696989914173889976925
        ///5191212388827998986649912824634749279971948589689238817721846893532697679994545789897911889729995897
        ///2168589418228699841979496964487152857627622699771987389157912193827151789199146397936892984945186648
        ///6173939628157711976563997464999974959831921613389971361747448844585131388314689679172394799717331399
        ///58 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day15 {
            get {
                return ResourceManager.GetString("Day15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1163751742
        ///1381373672
        ///2136511328
        ///3694931569
        ///7463417111
        ///1319128137
        ///1359912421
        ///3125421639
        ///1293138521
        ///2311944581.
        /// </summary>
        internal static string Day15Sample {
            get {
                return ResourceManager.GetString("Day15Sample", resourceCulture);
            }
        }
    }
}
